# Generated by Django 3.0.5 on 2020-04-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0002_beneficiario_borrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='borrar',
        ),
    ]
