# Generated by Django 3.0.5 on 2020-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_remove_beneficiario_borrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='cedula',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
