# Generated by Django 3.0.5 on 2020-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0004_auto_20200418_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='programa',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nangareko',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='pytyvo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
