# Generated by Django 3.0.5 on 2020-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0005_auto_20200418_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nangareko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'nangarekos',
            },
        ),
        migrations.CreateModel(
            name='Pytyvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'pytyvos',
            },
        ),
    ]
