# Generated by Django 3.0.5 on 2020-04-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0006_nangareko_pytyvo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='denuncia',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nangareko',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nombreApellido',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='pytyvo',
        ),
    ]
