# Generated by Django 3.0.5 on 2020-04-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0008_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jubilado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'jubilados',
            },
        ),
        migrations.CreateModel(
            name='MJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'mjs',
            },
        ),
        migrations.CreateModel(
            name='SET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'sets',
            },
        ),
        migrations.CreateModel(
            name='SFP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'sfps',
            },
        ),
        migrations.CreateModel(
            name='Tekopora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('nombreApellido', models.CharField(max_length=512)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'tekoporas',
            },
        ),
    ]
